name: rainbow_ai
description: AI Coloring Book for Toddlers
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.1
  image_gallery_saver: ^2.0.3
  flutter_colorpicker: ^1.0.3
  signature: ^5.4.0 # For the drawing canvas
